#!/usr/bin/env bun

import "../envConfig";

import { createHash } from "node:crypto";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { resolveRequiredDatabaseUrl } from "@/lib/mock-environment";
import * as schema from "../db/schema";
import { runMockDashboardSmokeChecks, waitForDatabaseReady } from "./mock-db-utils";

const pool = new Pool({ connectionString: resolveRequiredDatabaseUrl("mock") });
const db = drizzle(pool, { schema });

function daysAgo(days: number): Date {
	return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

function hoursAgo(hours: number): Date {
	return new Date(Date.now() - hours * 60 * 60 * 1000);
}

function toJson(value: unknown): string {
	return JSON.stringify(value);
}

function hashToken(value: string): string {
	return createHash("sha256").update(value).digest("hex");
}

async function seed() {
	console.info("🌱 Seeding mock database...");
	await waitForDatabaseReady(resolveRequiredDatabaseUrl("mock"), { label: "Mock database" });

	const [
		atlasApplicant,
		springvaleApplicant,
		meridianApplicant,
		redlineApplicant,
		northstarApplicant,
		harborApplicant,
	] =
		await db
			.insert(schema.applicants)
			.values([
				{
					companyName: "Atlas Facilities Group",
					tradingName: "Atlas Facilities",
					registrationNumber: "2021/184512/07",
					contactName: "Naledi Mokoena",
					idNumber: "8601014800086",
					email: "naledi@atlasfacilities.mock",
					phone: "+27825550101",
					businessType: "COMPANY",
					entityType: "company",
					productType: "premium_collections",
					industry: "Facilities Management",
					employeeCount: 84,
					mandateType: "DEBIT_ORDER",
					mandateVolume: 8500000,
					estimatedTransactionsPerMonth: 420,
					status: "qualified",
					riskLevel: "amber",
					itcScore: 642,
					itcStatus: "manual_review",
					sanctionStatus: "clear",
					accountExecutive: "ae_manual_mock",
					notes: "Manual testing seed: stage 4 risk review",
					createdAt: daysAgo(12),
					updatedAt: hoursAgo(7),
				},
				{
					companyName: "Springvale Care NPC",
					tradingName: "Springvale Care",
					registrationNumber: "2019/442211/08",
					contactName: "Tariro Dube",
					idNumber: "9002205800081",
					email: "tariro@springvale.mock",
					phone: "+27825550102",
					businessType: "NPO",
					entityType: "npo",
					productType: "standard",
					industry: "Healthcare",
					employeeCount: 26,
					mandateType: "EFT",
					mandateVolume: 3100000,
					estimatedTransactionsPerMonth: 95,
					status: "documents_pending",
					riskLevel: "green",
					itcScore: 701,
					itcStatus: "clear",
					sanctionStatus: "clear",
					accountExecutive: "ae_manual_mock",
					notes: "Manual testing seed: stage 3 docs and FICA",
					createdAt: daysAgo(8),
					updatedAt: hoursAgo(4),
				},
				{
					companyName: "Meridian Retail CC",
					tradingName: "Meridian Retail",
					registrationNumber: "2017/101010/23",
					contactName: "Ayesha Khan",
					idNumber: "9203036500087",
					email: "ayesha@meridian.mock",
					phone: "+27825550103",
					businessType: "CLOSE_CORPORATION",
					entityType: "close_corporation",
					productType: "call_centre",
					industry: "Retail",
					employeeCount: 132,
					mandateType: "DEBIT_ORDER",
					mandateVolume: 12400000,
					estimatedTransactionsPerMonth: 780,
					status: "approved",
					riskLevel: "green",
					itcScore: 744,
					itcStatus: "clear",
					sanctionStatus: "clear",
					accountExecutive: "ae_growth_mock",
					notes: "Manual testing seed: completed happy path",
					createdAt: daysAgo(20),
					updatedAt: daysAgo(1),
				},
				{
					companyName: "Redline Logistics Pty Ltd",
					tradingName: "Redline Logistics",
					registrationNumber: "2020/331144/07",
					contactName: "Mandla Sithole",
					idNumber: "8509095700083",
					email: "mandla@redline.mock",
					phone: "+27825550104",
					businessType: "COMPANY",
					entityType: "company",
					productType: "standard",
					industry: "Transport",
					employeeCount: 47,
					mandateType: "EFT",
					mandateVolume: 2800000,
					estimatedTransactionsPerMonth: 120,
					status: "declined",
					riskLevel: "red",
					itcScore: 402,
					itcStatus: "failed",
					sanctionStatus: "flagged",
					accountExecutive: "ae_manual_mock",
					notes: "Manual testing seed: terminated sanctions case",
					createdAt: daysAgo(16),
					updatedAt: daysAgo(2),
				},
				{
					companyName: "Northstar Office Supplies Pty Ltd",
					tradingName: "Northstar Office Supplies",
					registrationNumber: "2022/550321/07",
					contactName: "Lerato Molefe",
					idNumber: "9105156400080",
					email: "lerato@northstar.mock",
					phone: "+27825550105",
					businessType: "COMPANY",
					entityType: "company",
					productType: "standard",
					industry: "Office Supplies",
					employeeCount: 58,
					mandateType: "DEBIT_ORDER",
					mandateVolume: 6400000,
					estimatedTransactionsPerMonth: 265,
					status: "qualified",
					riskLevel: "green",
					itcScore: 792,
					itcStatus: "clear",
					sanctionStatus: "clear",
					accountExecutive: "ae_green_lane_mock",
					notes: "Manual testing seed: green lane candidate",
					createdAt: daysAgo(11),
					updatedAt: hoursAgo(2),
				},
				{
					companyName: "Harbor Community Services",
					tradingName: "Harbor Community Services",
					registrationNumber: "2023/770114/08",
					contactName: "Zanele Jacobs",
					idNumber: "9308087300089",
					email: "zanele@harbor.mock",
					phone: "+27825550106",
					businessType: "NPO",
					entityType: "npo",
					productType: "standard",
					industry: "Community Services",
					employeeCount: 19,
					mandateType: "EFT",
					mandateVolume: 1900000,
					estimatedTransactionsPerMonth: 60,
					status: "documents_pending",
					riskLevel: "amber",
					itcScore: 688,
					itcStatus: "clear",
					sanctionStatus: "clear",
					accountExecutive: "ae_fica_mock",
					notes: "Manual testing seed: FICA red/manual review",
					createdAt: daysAgo(7),
					updatedAt: hoursAgo(1),
				},
			])
			.returning();

	const [atlasWorkflow] = await db
		.insert(schema.workflows)
		.values({
			applicantId: atlasApplicant.id,
			stage: 4,
			status: "awaiting_human",
			startedAt: daysAgo(12),
			procurementCleared: true,
			documentsComplete: true,
			aiAnalysisComplete: true,
			salesEvaluationStatus: "approved",
			preRiskRequired: true,
			preRiskOutcome: "approved",
			preRiskEvaluatedAt: daysAgo(10),
			stageName: "Risk Review",
			currentAgent: "reporter",
			reviewType: "general",
			decisionType: "risk_review",
			targetResource: "/api/risk-review",
			stateLockVersion: 4,
			metadata: toJson({ seedProfile: "manual-risk-review" }),
		})
		.returning();

	const [springvaleWorkflow] = await db
		.insert(schema.workflows)
		.values({
			applicantId: springvaleApplicant.id,
			stage: 3,
			status: "processing",
			startedAt: daysAgo(8),
			procurementCleared: true,
			documentsComplete: false,
			aiAnalysisComplete: false,
			salesEvaluationStatus: "approved",
			preRiskRequired: false,
			preRiskOutcome: "skipped",
			stageName: "FICA Collection",
			currentAgent: "validation",
			reviewType: "general",
			decisionType: "document_review",
			targetResource: "/api/onboarding/documents/upload",
			stateLockVersion: 2,
			metadata: toJson({ seedProfile: "manual-fica-pending" }),
		})
		.returning();

	const [meridianWorkflow] = await db
		.insert(schema.workflows)
		.values({
			applicantId: meridianApplicant.id,
			stage: 6,
			status: "completed",
			startedAt: daysAgo(20),
			completedAt: daysAgo(1),
			procurementCleared: true,
			documentsComplete: true,
			aiAnalysisComplete: true,
			mandateRetryCount: 1,
			mandateLastSentAt: daysAgo(6),
			riskManagerApproval: toJson({
				approvedBy: "risk_manager_mock",
				decision: "approved",
			}),
			accountManagerApproval: toJson({
				approvedBy: "account_manager_mock",
				decision: "approved",
			}),
			contractDraftReviewedBy: "legal_mock",
			absaPacketSentAt: daysAgo(4),
			absaPacketSentBy: "ops_mock",
			absaApprovalConfirmedBy: "absa_mock",
			salesEvaluationStatus: "approved",
			preRiskRequired: false,
			preRiskOutcome: "skipped",
			applicantDecisionOutcome: "approved",
			stageName: "Final Approval",
			currentAgent: "reporter",
			reviewType: "general",
			decisionType: "final_approval",
			targetResource: "/api/contract/finalize",
			stateLockVersion: 7,
			metadata: toJson({ seedProfile: "manual-complete" }),
		})
		.returning();

	const [redlineWorkflow] = await db
		.insert(schema.workflows)
		.values({
			applicantId: redlineApplicant.id,
			stage: 4,
			status: "terminated",
			startedAt: daysAgo(16),
			terminatedAt: daysAgo(2),
			terminatedBy: "risk_manager_mock",
			terminationReason: "SANCTIONS_EXTERNAL_BLOCKED",
			procurementCleared: false,
			documentsComplete: true,
			aiAnalysisComplete: true,
			salesEvaluationStatus: "issues_found",
			preRiskRequired: true,
			preRiskOutcome: "rejected",
			preRiskEvaluatedAt: daysAgo(3),
			stageName: "Terminated",
			currentAgent: "sanctions",
			reviewType: "general",
			decisionType: "risk_review",
			targetResource: "/api/sanctions",
			stateLockVersion: 5,
			metadata: toJson({ seedProfile: "manual-terminated" }),
		})
		.returning();

	const [northstarWorkflow] = await db
		.insert(schema.workflows)
		.values({
			applicantId: northstarApplicant.id,
			stage: 4,
			status: "awaiting_human",
			startedAt: daysAgo(11),
			procurementCleared: true,
			documentsComplete: true,
			aiAnalysisComplete: true,
			salesEvaluationStatus: "approved",
			preRiskRequired: false,
			preRiskOutcome: "skipped",
			stageName: "Risk Review",
			currentAgent: "reporter",
			reviewType: "general",
			decisionType: "risk_review",
			targetResource: "/api/risk-review",
			stateLockVersion: 3,
			metadata: toJson({ seedProfile: "green-lane-candidate" }),
		})
		.returning();

	const [harborWorkflow] = await db
		.insert(schema.workflows)
		.values({
			applicantId: harborApplicant.id,
			stage: 3,
			status: "processing",
			startedAt: daysAgo(7),
			procurementCleared: true,
			documentsComplete: false,
			aiAnalysisComplete: false,
			salesEvaluationStatus: "approved",
			preRiskRequired: false,
			preRiskOutcome: "skipped",
			stageName: "FICA Collection",
			currentAgent: "validation",
			reviewType: "general",
			decisionType: "document_review",
			targetResource: "/api/onboarding/documents/upload",
			stateLockVersion: 2,
			metadata: toJson({ seedProfile: "fica-red" }),
		})
		.returning();

	await db.insert(schema.riskAssessments).values([
		{
			applicantId: atlasApplicant.id,
			overallScore: 63,
			overallStatus: "REVIEW_REQUIRED",
			overallRisk: "amber",
			procurementData: toJson({ status: "mock_clear", provider: "procurecheck-mock" }),
			itcData: toJson({ status: "manual_review", score: 642, provider: "itc-mock" }),
			sanctionsData: toJson({ status: "clear", provider: "sanctions-mock" }),
			ficaData: toJson({ status: "verified", provider: "fica-mock" }),
			cashFlowConsistency: "stable",
			dishonouredPayments: 1,
			averageDailyBalance: 187500,
			accountMatchVerified: "yes",
			letterheadVerified: "yes",
			aiAnalysis: toJson({ recommendation: "MANUAL_REVIEW", confidence: 74 }),
			reviewedBy: "risk_manager_mock",
			reviewedAt: hoursAgo(5),
			notes: "Needs manual pricing approval due to concentration risk.",
			createdAt: daysAgo(9),
		},
		{
			applicantId: springvaleApplicant.id,
			overallScore: 78,
			overallStatus: "COMPLIANT",
			overallRisk: "green",
			procurementData: toJson({ status: "mock_clear", provider: "procurecheck-mock" }),
			itcData: toJson({ status: "clear", score: 701, provider: "itc-mock" }),
			sanctionsData: toJson({ status: "clear", provider: "sanctions-mock" }),
			ficaData: toJson({ status: "pending_additional_docs", provider: "fica-mock" }),
			cashFlowConsistency: "regular",
			dishonouredPayments: 0,
			averageDailyBalance: 92500,
			accountMatchVerified: "yes",
			letterheadVerified: "pending",
			aiAnalysis: toJson({ recommendation: "APPROVE_WITH_CONDITIONS", confidence: 82 }),
			notes: "Awaiting latest proof of address upload.",
			createdAt: daysAgo(6),
		},
		{
			applicantId: meridianApplicant.id,
			overallScore: 91,
			overallStatus: "COMPLIANT",
			overallRisk: "green",
			procurementData: toJson({ status: "mock_clear", provider: "procurecheck-mock" }),
			itcData: toJson({ status: "clear", score: 744, provider: "itc-mock" }),
			sanctionsData: toJson({ status: "clear", provider: "sanctions-mock" }),
			ficaData: toJson({ status: "verified", provider: "fica-mock" }),
			cashFlowConsistency: "strong",
			dishonouredPayments: 0,
			averageDailyBalance: 345000,
			accountMatchVerified: "yes",
			letterheadVerified: "yes",
			aiAnalysis: toJson({ recommendation: "APPROVE", confidence: 93 }),
			reviewedBy: "risk_manager_mock",
			reviewedAt: daysAgo(3),
			notes: "Approved for standard pricing band.",
			createdAt: daysAgo(15),
		},
		{
			applicantId: redlineApplicant.id,
			overallScore: 29,
			overallStatus: "DECLINE",
			overallRisk: "red",
			procurementData: toJson({ status: "flagged", provider: "procurecheck-mock" }),
			itcData: toJson({ status: "failed", score: 402, provider: "itc-mock" }),
			sanctionsData: toJson({ status: "confirmed_hit", provider: "sanctions-mock" }),
			ficaData: toJson({ status: "verified", provider: "fica-mock" }),
			cashFlowConsistency: "volatile",
			dishonouredPayments: 5,
			averageDailyBalance: 21000,
			accountMatchVerified: "yes",
			letterheadVerified: "yes",
			aiAnalysis: toJson({ recommendation: "DECLINE", confidence: 97 }),
			reviewedBy: "risk_manager_mock",
			reviewedAt: daysAgo(2),
			notes: "Terminated due to sanctions evidence match.",
			createdAt: daysAgo(10),
		},
		{
			applicantId: northstarApplicant.id,
			overallScore: 94,
			overallStatus: "COMPLIANT",
			overallRisk: "green",
			procurementData: toJson({ status: "mock_clear", provider: "procurecheck-mock" }),
			itcData: toJson({ status: "clear", score: 792, provider: "itc-mock" }),
			sanctionsData: toJson({ status: "clear", provider: "sanctions-mock" }),
			ficaData: toJson({ status: "verified", provider: "fica-mock" }),
			cashFlowConsistency: "strong",
			dishonouredPayments: 0,
			averageDailyBalance: 228000,
			accountMatchVerified: "yes",
			letterheadVerified: "yes",
			aiAnalysis: toJson({ recommendation: "APPROVE", confidence: 96 }),
			reviewedBy: "risk_manager_mock",
			reviewedAt: daysAgo(4),
			notes: "Green Lane candidate with all four checks clean.",
			createdAt: daysAgo(8),
		},
		{
			applicantId: harborApplicant.id,
			overallScore: 52,
			overallStatus: "REVIEW_REQUIRED",
			overallRisk: "amber",
			procurementData: toJson({ status: "mock_clear", provider: "procurecheck-mock" }),
			itcData: toJson({ status: "clear", score: 688, provider: "itc-mock" }),
			sanctionsData: toJson({ status: "clear", provider: "sanctions-mock" }),
			ficaData: toJson({ status: "rejected", provider: "fica-mock" }),
			cashFlowConsistency: "regular",
			dishonouredPayments: 0,
			averageDailyBalance: 71200,
			accountMatchVerified: "no",
			letterheadVerified: "no",
			aiAnalysis: toJson({ recommendation: "MANUAL_REVIEW", confidence: 68 }),
			notes: "FICA mismatch scenario for manual testing.",
			createdAt: daysAgo(5),
		},
	]);

	await db.insert(schema.riskCheckResults).values([
		{
			workflowId: atlasWorkflow.id,
			applicantId: atlasApplicant.id,
			checkType: "PROCUREMENT",
			machineState: "completed",
			reviewState: "approved",
			provider: "procurecheck-mock",
			externalCheckId: "PROC-MOCK-ATLAS-001",
			payload: toJson({ status: "clear", score: 88 }),
			rawPayload: toJson({ source: "mock", supplierMatch: false }),
			startedAt: daysAgo(11),
			completedAt: daysAgo(11),
			reviewedBy: "risk_manager_mock",
			reviewedAt: daysAgo(10),
			reviewNotes: "No adverse findings.",
		},
		{
			workflowId: atlasWorkflow.id,
			applicantId: atlasApplicant.id,
			checkType: "ITC",
			machineState: "completed",
			reviewState: "acknowledged",
			provider: "itc-mock",
			externalCheckId: "ITC-MOCK-ATLAS-001",
			payload: toJson({ recommendation: "MANUAL_REVIEW", creditScore: 642 }),
			rawPayload: toJson({ source: "mock", adverseListings: 1 }),
			startedAt: daysAgo(11),
			completedAt: daysAgo(11),
			reviewNotes: "Manual reviewer to confirm affordability.",
		},
		{
			workflowId: atlasWorkflow.id,
			applicantId: atlasApplicant.id,
			checkType: "SANCTIONS",
			machineState: "completed",
			reviewState: "approved",
			provider: "sanctions-mock",
			externalCheckId: "SAN-MOCK-ATLAS-001",
			payload: toJson({ status: "clear" }),
			rawPayload: toJson({ source: "mock", matchCount: 0 }),
			startedAt: daysAgo(11),
			completedAt: daysAgo(11),
		},
		{
			workflowId: atlasWorkflow.id,
			applicantId: atlasApplicant.id,
			checkType: "FICA",
			machineState: "completed",
			reviewState: "approved",
			provider: "fica-mock",
			externalCheckId: "FICA-MOCK-ATLAS-001",
			payload: toJson({ verificationStatus: "verified" }),
			rawPayload: toJson({ source: "mock", bankStatementVerified: true }),
			startedAt: daysAgo(10),
			completedAt: daysAgo(10),
		},
		{
			workflowId: springvaleWorkflow.id,
			applicantId: springvaleApplicant.id,
			checkType: "PROCUREMENT",
			machineState: "completed",
			reviewState: "approved",
			provider: "procurecheck-mock",
			externalCheckId: "PROC-MOCK-SPRING-001",
			payload: toJson({ status: "clear", score: 91 }),
			rawPayload: toJson({ source: "mock" }),
			startedAt: daysAgo(7),
			completedAt: daysAgo(7),
		},
		{
			workflowId: springvaleWorkflow.id,
			applicantId: springvaleApplicant.id,
			checkType: "ITC",
			machineState: "completed",
			reviewState: "approved",
			provider: "itc-mock",
			externalCheckId: "ITC-MOCK-SPRING-001",
			payload: toJson({ recommendation: "APPROVE", creditScore: 701 }),
			rawPayload: toJson({ source: "mock", adverseListings: 0 }),
			startedAt: daysAgo(7),
			completedAt: daysAgo(7),
		},
		{
			workflowId: springvaleWorkflow.id,
			applicantId: springvaleApplicant.id,
			checkType: "SANCTIONS",
			machineState: "completed",
			reviewState: "approved",
			provider: "sanctions-mock",
			externalCheckId: "SAN-MOCK-SPRING-001",
			payload: toJson({ status: "clear" }),
			rawPayload: toJson({ source: "mock", matchCount: 0 }),
			startedAt: daysAgo(7),
			completedAt: daysAgo(7),
		},
		{
			workflowId: springvaleWorkflow.id,
			applicantId: springvaleApplicant.id,
			checkType: "FICA",
			machineState: "manual_required",
			reviewState: "pending",
			provider: "fica-mock",
			externalCheckId: "FICA-MOCK-SPRING-001",
			payload: toJson({ verificationStatus: "pending_additional_docs" }),
			rawPayload: toJson({ source: "mock", missingDocument: "PROOF_OF_ADDRESS" }),
			startedAt: daysAgo(6),
			completedAt: daysAgo(6),
			errorDetails: "Awaiting current proof of address.",
		},
		{
			workflowId: meridianWorkflow.id,
			applicantId: meridianApplicant.id,
			checkType: "PROCUREMENT",
			machineState: "completed",
			reviewState: "approved",
			provider: "procurecheck-mock",
			externalCheckId: "PROC-MOCK-MERIDIAN-001",
			payload: toJson({ status: "clear", score: 95 }),
			rawPayload: toJson({ source: "mock" }),
			startedAt: daysAgo(18),
			completedAt: daysAgo(18),
		},
		{
			workflowId: meridianWorkflow.id,
			applicantId: meridianApplicant.id,
			checkType: "ITC",
			machineState: "completed",
			reviewState: "approved",
			provider: "itc-mock",
			externalCheckId: "ITC-MOCK-MERIDIAN-001",
			payload: toJson({ recommendation: "APPROVE", creditScore: 744 }),
			rawPayload: toJson({ source: "mock", adverseListings: 0 }),
			startedAt: daysAgo(18),
			completedAt: daysAgo(18),
		},
		{
			workflowId: meridianWorkflow.id,
			applicantId: meridianApplicant.id,
			checkType: "SANCTIONS",
			machineState: "completed",
			reviewState: "approved",
			provider: "sanctions-mock",
			externalCheckId: "SAN-MOCK-MERIDIAN-001",
			payload: toJson({ status: "clear" }),
			rawPayload: toJson({ source: "mock", matchCount: 0 }),
			startedAt: daysAgo(18),
			completedAt: daysAgo(18),
		},
		{
			workflowId: meridianWorkflow.id,
			applicantId: meridianApplicant.id,
			checkType: "FICA",
			machineState: "completed",
			reviewState: "approved",
			provider: "fica-mock",
			externalCheckId: "FICA-MOCK-MERIDIAN-001",
			payload: toJson({ verificationStatus: "verified" }),
			rawPayload: toJson({ source: "mock", bankStatementVerified: true }),
			startedAt: daysAgo(17),
			completedAt: daysAgo(17),
		},
		{
			workflowId: redlineWorkflow.id,
			applicantId: redlineApplicant.id,
			checkType: "PROCUREMENT",
			machineState: "failed",
			reviewState: "rejected",
			provider: "procurecheck-mock",
			externalCheckId: "PROC-MOCK-REDLINE-001",
			payload: toJson({ status: "flagged" }),
			rawPayload: toJson({ source: "mock", conflictCount: 2 }),
			startedAt: daysAgo(4),
			completedAt: daysAgo(4),
			errorDetails: "Procurement watchlist conflict.",
		},
		{
			workflowId: redlineWorkflow.id,
			applicantId: redlineApplicant.id,
			checkType: "ITC",
			machineState: "failed",
			reviewState: "rejected",
			provider: "itc-mock",
			externalCheckId: "ITC-MOCK-REDLINE-001",
			payload: toJson({ recommendation: "DECLINE", creditScore: 402 }),
			rawPayload: toJson({ source: "mock", adverseListings: 4 }),
			startedAt: daysAgo(4),
			completedAt: daysAgo(4),
			errorDetails: "High adverse credit exposure.",
		},
		{
			workflowId: redlineWorkflow.id,
			applicantId: redlineApplicant.id,
			checkType: "SANCTIONS",
			machineState: "failed",
			reviewState: "rejected",
			provider: "sanctions-mock",
			externalCheckId: "SAN-MOCK-REDLINE-001",
			payload: toJson({ status: "confirmed_hit" }),
			rawPayload: toJson({ source: "mock", matchCount: 1, list: "OFAC" }),
			startedAt: daysAgo(3),
			completedAt: daysAgo(3),
			errorDetails: "Confirmed sanctions hit.",
		},
		{
			workflowId: redlineWorkflow.id,
			applicantId: redlineApplicant.id,
			checkType: "FICA",
			machineState: "completed",
			reviewState: "approved",
			provider: "fica-mock",
			externalCheckId: "FICA-MOCK-REDLINE-001",
			payload: toJson({ verificationStatus: "verified" }),
			rawPayload: toJson({ source: "mock" }),
			startedAt: daysAgo(5),
			completedAt: daysAgo(5),
		},
		{
			workflowId: northstarWorkflow.id,
			applicantId: northstarApplicant.id,
			checkType: "PROCUREMENT",
			machineState: "completed",
			reviewState: "approved",
			provider: "procurecheck-mock",
			externalCheckId: "PROC-MOCK-NORTHSTAR-001",
			payload: toJson({ anomalies: [], riskScore: 96, recommendedAction: "APPROVE" }),
			rawPayload: toJson({ source: "mock", flags: [] }),
			startedAt: daysAgo(9),
			completedAt: daysAgo(9),
		},
		{
			workflowId: northstarWorkflow.id,
			applicantId: northstarApplicant.id,
			checkType: "ITC",
			machineState: "completed",
			reviewState: "approved",
			provider: "itc-mock",
			externalCheckId: "ITC-MOCK-NORTHSTAR-001",
			payload: toJson({
				recommendation: "AUTO_APPROVE",
				creditScore: 792,
				riskCategory: "LOW",
				adverseListings: [],
			}),
			rawPayload: toJson({
				source: "mock",
				adverseListings: [],
				creditProfile: { riskCategory: "LOW" },
			}),
			startedAt: daysAgo(9),
			completedAt: daysAgo(9),
		},
		{
			workflowId: northstarWorkflow.id,
			applicantId: northstarApplicant.id,
			checkType: "SANCTIONS",
			machineState: "completed",
			reviewState: "approved",
			provider: "sanctions-mock",
			externalCheckId: "SAN-MOCK-NORTHSTAR-001",
			payload: toJson({ riskLevel: "CLEAR", isBlocked: false }),
			rawPayload: toJson({ source: "mock", matchCount: 0 }),
			startedAt: daysAgo(9),
			completedAt: daysAgo(9),
		},
		{
			workflowId: northstarWorkflow.id,
			applicantId: northstarApplicant.id,
			checkType: "FICA",
			machineState: "completed",
			reviewState: "approved",
			provider: "fica-mock",
			externalCheckId: "FICA-MOCK-NORTHSTAR-001",
			payload: toJson({
				summary: { overallRecommendation: "PROCEED", criticalMismatchCount: 0 },
				verificationStatus: "verified",
			}),
			rawPayload: toJson({ source: "mock", bankStatementVerified: true }),
			startedAt: daysAgo(8),
			completedAt: daysAgo(8),
		},
		{
			workflowId: harborWorkflow.id,
			applicantId: harborApplicant.id,
			checkType: "PROCUREMENT",
			machineState: "completed",
			reviewState: "approved",
			provider: "procurecheck-mock",
			externalCheckId: "PROC-MOCK-HARBOR-001",
			payload: toJson({ anomalies: [], riskScore: 89, recommendedAction: "APPROVE" }),
			rawPayload: toJson({ source: "mock", flags: [] }),
			startedAt: daysAgo(6),
			completedAt: daysAgo(6),
		},
		{
			workflowId: harborWorkflow.id,
			applicantId: harborApplicant.id,
			checkType: "ITC",
			machineState: "completed",
			reviewState: "approved",
			provider: "itc-mock",
			externalCheckId: "ITC-MOCK-HARBOR-001",
			payload: toJson({
				recommendation: "AUTO_APPROVE",
				creditScore: 688,
				riskCategory: "LOW",
				adverseListings: [],
			}),
			rawPayload: toJson({
				source: "mock",
				adverseListings: [],
				creditProfile: { riskCategory: "LOW" },
			}),
			startedAt: daysAgo(6),
			completedAt: daysAgo(6),
		},
		{
			workflowId: harborWorkflow.id,
			applicantId: harborApplicant.id,
			checkType: "SANCTIONS",
			machineState: "completed",
			reviewState: "approved",
			provider: "sanctions-mock",
			externalCheckId: "SAN-MOCK-HARBOR-001",
			payload: toJson({ riskLevel: "CLEAR", isBlocked: false }),
			rawPayload: toJson({ source: "mock", matchCount: 0 }),
			startedAt: daysAgo(6),
			completedAt: daysAgo(6),
		},
		{
			workflowId: harborWorkflow.id,
			applicantId: harborApplicant.id,
			checkType: "FICA",
			machineState: "manual_required",
			reviewState: "pending",
			provider: "fica-mock",
			externalCheckId: "FICA-MOCK-HARBOR-001",
			payload: toJson({
				summary: { overallRecommendation: "HOLD", criticalMismatchCount: 2 },
				verificationStatus: "rejected",
			}),
			rawPayload: toJson({
				source: "mock",
				reasons: ["name_mismatch", "address_mismatch"],
			}),
			startedAt: daysAgo(5),
			completedAt: daysAgo(5),
			errorDetails: "Critical FICA mismatches detected.",
		},
	]);

	await db.insert(schema.quotes).values([
		{
			applicantId: atlasApplicant.id,
			workflowId: atlasWorkflow.id,
			amount: 145000,
			baseFeePercent: 185,
			adjustedFeePercent: 210,
			details: toJson({ monthlyVolumeBand: "high", riskAdjustment: "amber" }),
			rationale: "Mock quote with manual review uplift.",
			status: "pending_approval",
			generatedBy: "gemini",
			createdAt: daysAgo(9),
			updatedAt: hoursAgo(6),
		},
		{
			applicantId: meridianApplicant.id,
			workflowId: meridianWorkflow.id,
			amount: 98000,
			baseFeePercent: 150,
			adjustedFeePercent: 150,
			details: toJson({ monthlyVolumeBand: "enterprise", riskAdjustment: "green" }),
			rationale: "Mock quote approved on standard pricing.",
			status: "approved",
			generatedBy: "gemini",
			createdAt: daysAgo(14),
			updatedAt: daysAgo(3),
		},
		{
			applicantId: northstarApplicant.id,
			workflowId: northstarWorkflow.id,
			amount: 112000,
			baseFeePercent: 145,
			adjustedFeePercent: 145,
			details: toJson({ monthlyVolumeBand: "mid", riskAdjustment: "green" }),
			rationale: "Green Lane candidate with all checks cleared.",
			status: "approved",
			generatedBy: "gemini",
			createdAt: daysAgo(8),
			updatedAt: daysAgo(2),
		},
	]);

	await db.insert(schema.workflowEvents).values([
		{
			workflowId: atlasWorkflow.id,
			eventType: "risk_review_requested",
			payload: toJson({ reason: "itc_manual_review" }),
			timestamp: hoursAgo(8),
			actorType: "system",
		},
		{
			workflowId: springvaleWorkflow.id,
			eventType: "fica_documents_missing",
			payload: toJson({ missing: ["PROOF_OF_ADDRESS"] }),
			timestamp: hoursAgo(4),
			actorType: "platform",
		},
		{
			workflowId: meridianWorkflow.id,
			eventType: "workflow_completed",
			payload: toJson({ approvedBy: ["risk_manager_mock", "account_manager_mock"] }),
			timestamp: daysAgo(1),
			actorType: "platform",
		},
		{
			workflowId: redlineWorkflow.id,
			eventType: "kill_switch_executed",
			payload: toJson({ reason: "SANCTIONS_EXTERNAL_BLOCKED" }),
			timestamp: daysAgo(2),
			actorType: "system",
		},
		{
			workflowId: northstarWorkflow.id,
			eventType: "signed_quote_received",
			payload: toJson({ source: "mock_seed" }),
			timestamp: daysAgo(8),
			actorType: "platform",
		},
		{
			workflowId: harborWorkflow.id,
			eventType: "fica_check_completed",
			payload: toJson({ outcome: "manual_required", reason: "critical_mismatch" }),
			timestamp: daysAgo(5),
			actorType: "platform",
		},
	]);

	await db.insert(schema.notifications).values([
		{
			workflowId: atlasWorkflow.id,
			applicantId: atlasApplicant.id,
			type: "risk_review_required",
			message: "Atlas Facilities requires manual risk review before quote approval.",
			read: false,
			actionable: true,
			severity: "high",
			groupKey: "manual-risk-review",
			createdAt: hoursAgo(6),
		},
		{
			workflowId: springvaleWorkflow.id,
			applicantId: springvaleApplicant.id,
			type: "document_missing",
			message: "Springvale Care is still missing a current proof of address.",
			read: false,
			actionable: true,
			severity: "medium",
			groupKey: "fica-followup",
			createdAt: hoursAgo(3),
		},
		{
			workflowId: meridianWorkflow.id,
			applicantId: meridianApplicant.id,
			type: "workflow_completed",
			message: "Meridian Retail completed onboarding successfully.",
			read: true,
			actionable: false,
			severity: "low",
			groupKey: "workflow-complete",
			createdAt: daysAgo(1),
		},
		{
			workflowId: redlineWorkflow.id,
			applicantId: redlineApplicant.id,
			type: "kill_switch_executed",
			message: "Redline Logistics was terminated after a confirmed sanctions hit.",
			read: false,
			actionable: false,
			severity: "critical",
			groupKey: "terminated-sanctions",
			createdAt: daysAgo(2),
		},
		{
			workflowId: northstarWorkflow.id,
			applicantId: northstarApplicant.id,
			type: "green_lane_candidate",
			message: "Northstar Office Supplies is ready for Green Lane testing.",
			read: false,
			actionable: true,
			severity: "medium",
			groupKey: "green-lane-candidate",
			createdAt: hoursAgo(2),
		},
		{
			workflowId: harborWorkflow.id,
			applicantId: harborApplicant.id,
			type: "fica_manual_review_required",
			message: "Harbor Community Services failed FICA and needs manual review.",
			read: false,
			actionable: true,
			severity: "high",
			groupKey: "fica-red",
			createdAt: hoursAgo(1),
		},
	]);

	const [springvaleForm, meridianForm, harborForm] = await db
		.insert(schema.internalForms)
		.values([
			{
				workflowId: springvaleWorkflow.id,
				formType: "fica_documents",
				status: "in_progress",
				currentStep: 2,
				totalSteps: 4,
				lastSavedAt: hoursAgo(5),
				createdAt: daysAgo(6),
				updatedAt: hoursAgo(5),
			},
			{
				workflowId: meridianWorkflow.id,
				formType: "absa_6995",
				status: "approved",
				currentStep: 3,
				totalSteps: 3,
				submittedAt: daysAgo(5),
				reviewedAt: daysAgo(4),
				reviewedBy: "ops_mock",
				reviewNotes: "Approved and dispatched.",
				createdAt: daysAgo(7),
				updatedAt: daysAgo(4),
			},
			{
				workflowId: harborWorkflow.id,
				formType: "fica_documents",
				status: "revision_required",
				currentStep: 3,
				totalSteps: 4,
				submittedAt: daysAgo(5),
				reviewNotes: "Name and address mismatches require resubmission.",
				createdAt: daysAgo(6),
				updatedAt: hoursAgo(1),
			},
		])
		.returning();

	await db.insert(schema.internalSubmissions).values([
		{
			internalFormId: springvaleForm.id,
			version: 2,
			formData: toJson({
				organisationType: "NPO",
				uploadedDocuments: ["BANK_STATEMENT"],
				missingDocuments: ["PROOF_OF_ADDRESS"],
			}),
			isDraft: true,
			submittedBy: "client_mock",
			createdAt: hoursAgo(5),
		},
		{
			internalFormId: meridianForm.id,
			version: 1,
			formData: toJson({
				branchCode: "632005",
				accountNumber: "1022334455",
				approvedBy: "ops_mock",
			}),
			isDraft: false,
			submittedBy: "ops_mock",
			createdAt: daysAgo(5),
		},
		{
			internalFormId: harborForm.id,
			version: 1,
			formData: toJson({
				organisationType: "NPO",
				uploadedDocuments: ["BANK_STATEMENT", "PROOF_OF_ADDRESS"],
				finding: "critical_fica_mismatch",
			}),
			isDraft: false,
			submittedBy: "client_mock",
			createdAt: daysAgo(5),
		},
	]);

	await db.insert(schema.documentUploads).values([
		{
			workflowId: springvaleWorkflow.id,
			internalFormId: springvaleForm.id,
			category: "financial",
			documentType: "BANK_STATEMENT",
			fileName: "springvale-bank-statement.pdf",
			fileSize: 182044,
			fileContent: "mock-pdf-content",
			mimeType: "application/pdf",
			storageKey: "mock/springvale/bank-statement.pdf",
			storageUrl: "https://mock-storage.local/springvale/bank-statement.pdf",
			verificationStatus: "verified",
			verificationNotes: "Verified by mock FICA provider.",
			verifiedBy: "fica_mock_service",
			verifiedAt: daysAgo(5),
			uploadedBy: "client_mock",
			uploadedAt: daysAgo(6),
		},
		{
			workflowId: meridianWorkflow.id,
			internalFormId: meridianForm.id,
			category: "standard",
			documentType: "SERVICE_AGREEMENT",
			fileName: "meridian-service-agreement.pdf",
			fileSize: 264820,
			fileContent: "mock-pdf-content",
			mimeType: "application/pdf",
			storageKey: "mock/meridian/service-agreement.pdf",
			storageUrl: "https://mock-storage.local/meridian/service-agreement.pdf",
			verificationStatus: "verified",
			verificationNotes: "Approved for dispatch.",
			verifiedBy: "ops_mock",
			verifiedAt: daysAgo(4),
			uploadedBy: "ops_mock",
			uploadedAt: daysAgo(5),
		},
		{
			workflowId: harborWorkflow.id,
			internalFormId: harborForm.id,
			category: "financial",
			documentType: "BANK_STATEMENT",
			fileName: "harbor-bank-statement.pdf",
			fileSize: 173100,
			fileContent: "mock-pdf-content",
			mimeType: "application/pdf",
			storageKey: "mock/harbor/bank-statement.pdf",
			storageUrl: "https://mock-storage.local/harbor/bank-statement.pdf",
			verificationStatus: "rejected",
			verificationNotes: "Critical mismatches detected in mock FICA review.",
			verifiedBy: "fica_mock_service",
			verifiedAt: daysAgo(5),
			uploadedBy: "client_mock",
			uploadedAt: daysAgo(5),
		},
	]);

	await db.insert(schema.signatures).values([
		{
			workflowId: meridianWorkflow.id,
			internalFormId: meridianForm.id,
			signatoryName: "Ayesha Khan",
			signatoryRole: "Managing Member",
			signatoryIdNumber: "9203036500087",
			signatureData: "data:image/png;base64,mock-signature",
			signatureHash: hashToken("meridian-signature"),
			ipAddress: "127.0.0.1",
			userAgent: "mock-manual-testing-agent",
			signedAt: daysAgo(5),
		},
	]);

	await db.insert(schema.documents).values([
		{
			applicantId: atlasApplicant.id,
			type: "RISK_MEMO",
			status: "verified",
			category: "risk_based",
			source: "system",
			fileName: "atlas-risk-summary.json",
			fileContent: toJson({ recommendation: "manual_review" }),
			mimeType: "application/json",
			storageUrl: "https://mock-storage.local/atlas/risk-summary.json",
			uploadedBy: "system",
			uploadedAt: hoursAgo(6),
			verifiedAt: hoursAgo(5),
			processedAt: hoursAgo(5),
			processingStatus: "processed",
			processingResult: "manual_review",
			notes: "Generated from seeded mock analysis.",
		},
		{
			applicantId: springvaleApplicant.id,
			type: "PROOF_OF_ADDRESS",
			status: "pending",
			category: "fica_business",
			source: "client",
			fileName: "springvale-proof-of-address.pdf",
			mimeType: "application/pdf",
			notes: "Expected but not yet uploaded in seeded scenario.",
		},
		{
			applicantId: harborApplicant.id,
			type: "FICA_EXCEPTION_MEMO",
			status: "pending",
			category: "risk_based",
			source: "system",
			fileName: "harbor-fica-exception.json",
			fileContent: toJson({ criticalMismatchCount: 2, recommendation: "manual_review" }),
			mimeType: "application/json",
			storageUrl: "https://mock-storage.local/harbor/fica-exception.json",
			uploadedBy: "system",
			uploadedAt: hoursAgo(1),
			notes: "Generated from seeded FICA red scenario.",
		},
	]);

	await db.insert(schema.applicantMagiclinkForms).values([
		{
			applicantId: springvaleApplicant.id,
			workflowId: springvaleWorkflow.id,
			formType: "FACILITY_APPLICATION",
			status: "submitted",
			tokenHash: hashToken("springvale-facility-form"),
			token: "springvale-facility-form-token",
			tokenPrefix: "sprngv",
			sentAt: daysAgo(7),
			viewedAt: daysAgo(7),
			expiresAt: daysAgo(-7),
			submittedAt: daysAgo(6),
			createdAt: daysAgo(7),
		},
		{
			applicantId: atlasApplicant.id,
			workflowId: atlasWorkflow.id,
			formType: "SIGNED_QUOTATION",
			status: "viewed",
			tokenHash: hashToken("atlas-quote-form"),
			token: "atlas-quote-form-token",
			tokenPrefix: "atlasq",
			sentAt: daysAgo(9),
			viewedAt: daysAgo(8),
			expiresAt: daysAgo(-5),
			decisionStatus: "pending",
			createdAt: daysAgo(9),
		},
		{
			applicantId: northstarApplicant.id,
			workflowId: northstarWorkflow.id,
			formType: "SIGNED_QUOTATION",
			status: "submitted",
			tokenHash: hashToken("northstar-quote-form"),
			token: "northstar-quote-form-token",
			tokenPrefix: "nstarq",
			sentAt: daysAgo(9),
			viewedAt: daysAgo(9),
			expiresAt: daysAgo(-5),
			submittedAt: daysAgo(8),
			decisionStatus: "responded",
			decisionOutcome: "approved",
			decisionAt: daysAgo(8),
			createdAt: daysAgo(9),
		},
	]);

	await db.insert(schema.agents).values([
		{
			agentId: "risk_mock_agent",
			name: "Risk Mock Agent",
			description: "Deterministic risk reviewer for manual testing",
			taskType: "risk_verification",
			status: "active",
			callbackCount: 18,
			createdAt: daysAgo(30),
		},
		{
			agentId: "sanctions_mock_agent",
			name: "Sanctions Mock Agent",
			description: "Deterministic sanctions reviewer for manual testing",
			taskType: "risk_verification",
			status: "active",
			callbackCount: 12,
			createdAt: daysAgo(30),
		},
	]);

	await db.insert(schema.aiAnalysisLogs).values([
		{
			applicantId: atlasApplicant.id,
			workflowId: atlasWorkflow.id,
			agentName: "reporter",
			promptVersionId: "mock-seed-v1",
			confidenceScore: 74,
			narrative: "Manual review recommended due to moderate credit concentration risk.",
			rawOutput: toJson({ recommendation: "MANUAL_REVIEW" }),
			createdAt: hoursAgo(6),
		},
		{
			applicantId: meridianApplicant.id,
			workflowId: meridianWorkflow.id,
			agentName: "reporter",
			promptVersionId: "mock-seed-v1",
			confidenceScore: 93,
			narrative: "Approve with standard pricing and no additional interventions.",
			rawOutput: toJson({ recommendation: "APPROVE" }),
			createdAt: daysAgo(3),
		},
		{
			applicantId: northstarApplicant.id,
			workflowId: northstarWorkflow.id,
			agentName: "reporter",
			promptVersionId: "mock-seed-v1",
			confidenceScore: 96,
			narrative: "All Green Lane checks are satisfied. Workflow is eligible for bypass.",
			rawOutput: toJson({ recommendation: "APPROVE", greenLaneEligible: true }),
			createdAt: hoursAgo(2),
		},
		{
			applicantId: harborApplicant.id,
			workflowId: harborWorkflow.id,
			agentName: "reporter",
			promptVersionId: "mock-seed-v1",
			confidenceScore: 68,
			narrative: "FICA comparison found critical mismatches and requires intervention.",
			rawOutput: toJson({ recommendation: "MANUAL_REVIEW", criticalMismatchCount: 2 }),
			createdAt: hoursAgo(1),
		},
	]);

	await db.insert(schema.activityLogs).values([
		{
			applicantId: atlasApplicant.id,
			action: "manual_review_queued",
			description: "Workflow escalated for manual risk review.",
			performedBy: "system",
			createdAt: hoursAgo(7),
		},
		{
			applicantId: redlineApplicant.id,
			action: "workflow_terminated",
			description: "Workflow terminated due to sanctions match.",
			performedBy: "risk_manager_mock",
			createdAt: daysAgo(2),
		},
		{
			applicantId: northstarApplicant.id,
			action: "green_lane_candidate_ready",
			description: "Seeded workflow is ready for manual Green Lane testing.",
			performedBy: "system",
			createdAt: hoursAgo(2),
		},
		{
			applicantId: harborApplicant.id,
			action: "fica_manual_review_required",
			description: "Seeded workflow requires manual FICA review due to mismatches.",
			performedBy: "system",
			createdAt: hoursAgo(1),
		},
	]);

	await db.insert(schema.todos).values([
		{ description: "Review Atlas Facilities manual pricing decision", completed: false },
		{ description: "Follow up Springvale missing proof of address", completed: false },
		{ description: "Grant Green Lane to Northstar Office Supplies", completed: false },
		{ description: "Review Harbor Community Services FICA exception", completed: false },
		{ description: "Archive Redline sanctions termination record", completed: true },
	]);

	await runMockDashboardSmokeChecks(resolveRequiredDatabaseUrl("mock"));

	console.info("✅ Mock database seeded");
}

seed()
	.catch(error => {
		console.error("❌ Failed to seed mock database:", error);
		process.exit(1);
	})
	.finally(async () => {
		await pool.end();
	});
